### ISSUE TITLE
Is keeping all the old revisions of the design necessary?

### ISSUE THREAD

**Issue by thatging3rkid** [FIRST-Team-1699/2017-offseason-design#2]
One of the reasons we use version control is so that we can look back at older revisions without having to store it locally. Storing all the files on the GitHub doesn't make much sense unless there is something else going on behind the scenes that requires older revisions.

**Comment by squirlemaster42** [comment]
ATM I am not using a Git client to upload files. I just wanted to make sure that everything was working correctly. They will be removed at the end of the week.
